export const db = "main-permdal"
export const orderCollection = "bestellungen"
export const postCollection = "blog_beitraege"
export const eventCollection = "backoffice_ereignisse"
export const productsCollection = "produkte"
export const staffelCollection = "angebote"
