/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZentraleRouteImport } from './routes/zentrale'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StaffelnRouteImport } from './routes/staffeln'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProdukteRouteImport } from './routes/produkte'
import { Route as PermdalRouteImport } from './routes/permdal'
import { Route as MarktplatzRouteImport } from './routes/marktplatz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BestellungenRouteImport } from './routes/bestellungen'
import { Route as AgbsRouteImport } from './routes/agbs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZentraleIndexRouteImport } from './routes/zentrale.index'
import { Route as ZentraleOperationsRouteImport } from './routes/zentrale.operations'
import { Route as ZentraleCompactRouteImport } from './routes/zentrale.compact'
import { Route as ZentraleClassicRouteImport } from './routes/zentrale.classic'
import { Route as AngeboteIdRouteImport } from './routes/angebote.$id'
import { Route as UsersUserIdUserSlugRouteImport } from './routes/users.$userId.$userSlug'

const ZentraleRoute = ZentraleRouteImport.update({
  id: '/zentrale',
  path: '/zentrale',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffelnRoute = StaffelnRouteImport.update({
  id: '/staffeln',
  path: '/staffeln',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteRoute = ProdukteRouteImport.update({
  id: '/produkte',
  path: '/produkte',
  getParentRoute: () => rootRouteImport,
} as any)
const PermdalRoute = PermdalRouteImport.update({
  id: '/permdal',
  path: '/permdal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarktplatzRoute = MarktplatzRouteImport.update({
  id: '/marktplatz',
  path: '/marktplatz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungenRoute = BestellungenRouteImport.update({
  id: '/bestellungen',
  path: '/bestellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbsRoute = AgbsRouteImport.update({
  id: '/agbs',
  path: '/agbs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZentraleIndexRoute = ZentraleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZentraleRoute,
} as any)
const ZentraleOperationsRoute = ZentraleOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ZentraleRoute,
} as any)
const ZentraleCompactRoute = ZentraleCompactRouteImport.update({
  id: '/compact',
  path: '/compact',
  getParentRoute: () => ZentraleRoute,
} as any)
const ZentraleClassicRoute = ZentraleClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => ZentraleRoute,
} as any)
const AngeboteIdRoute = AngeboteIdRouteImport.update({
  id: '/angebote/$id',
  path: '/angebote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdUserSlugRoute = UsersUserIdUserSlugRouteImport.update({
  id: '/users/$userId/$userSlug',
  path: '/users/$userId/$userSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agbs': typeof AgbsRoute
  '/bestellungen': typeof BestellungenRoute
  '/blog': typeof BlogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/marktplatz': typeof MarktplatzRoute
  '/permdal': typeof PermdalRoute
  '/produkte': typeof ProdukteRoute
  '/signup': typeof SignupRoute
  '/staffeln': typeof StaffelnRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/zentrale': typeof ZentraleRouteWithChildren
  '/angebote/$id': typeof AngeboteIdRoute
  '/zentrale/classic': typeof ZentraleClassicRoute
  '/zentrale/compact': typeof ZentraleCompactRoute
  '/zentrale/operations': typeof ZentraleOperationsRoute
  '/zentrale/': typeof ZentraleIndexRoute
  '/users/$userId/$userSlug': typeof UsersUserIdUserSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agbs': typeof AgbsRoute
  '/bestellungen': typeof BestellungenRoute
  '/blog': typeof BlogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/marktplatz': typeof MarktplatzRoute
  '/permdal': typeof PermdalRoute
  '/produkte': typeof ProdukteRoute
  '/signup': typeof SignupRoute
  '/staffeln': typeof StaffelnRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/angebote/$id': typeof AngeboteIdRoute
  '/zentrale/classic': typeof ZentraleClassicRoute
  '/zentrale/compact': typeof ZentraleCompactRoute
  '/zentrale/operations': typeof ZentraleOperationsRoute
  '/zentrale': typeof ZentraleIndexRoute
  '/users/$userId/$userSlug': typeof UsersUserIdUserSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agbs': typeof AgbsRoute
  '/bestellungen': typeof BestellungenRoute
  '/blog': typeof BlogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/marktplatz': typeof MarktplatzRoute
  '/permdal': typeof PermdalRoute
  '/produkte': typeof ProdukteRoute
  '/signup': typeof SignupRoute
  '/staffeln': typeof StaffelnRoute
  '/team': typeof TeamRoute
  '/verify-email': typeof VerifyEmailRoute
  '/zentrale': typeof ZentraleRouteWithChildren
  '/angebote/$id': typeof AngeboteIdRoute
  '/zentrale/classic': typeof ZentraleClassicRoute
  '/zentrale/compact': typeof ZentraleCompactRoute
  '/zentrale/operations': typeof ZentraleOperationsRoute
  '/zentrale/': typeof ZentraleIndexRoute
  '/users/$userId/$userSlug': typeof UsersUserIdUserSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agbs'
    | '/bestellungen'
    | '/blog'
    | '/datenschutz'
    | '/impressum'
    | '/konto'
    | '/login'
    | '/marktplatz'
    | '/permdal'
    | '/produkte'
    | '/signup'
    | '/staffeln'
    | '/team'
    | '/verify-email'
    | '/zentrale'
    | '/angebote/$id'
    | '/zentrale/classic'
    | '/zentrale/compact'
    | '/zentrale/operations'
    | '/zentrale/'
    | '/users/$userId/$userSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agbs'
    | '/bestellungen'
    | '/blog'
    | '/datenschutz'
    | '/impressum'
    | '/konto'
    | '/login'
    | '/marktplatz'
    | '/permdal'
    | '/produkte'
    | '/signup'
    | '/staffeln'
    | '/team'
    | '/verify-email'
    | '/angebote/$id'
    | '/zentrale/classic'
    | '/zentrale/compact'
    | '/zentrale/operations'
    | '/zentrale'
    | '/users/$userId/$userSlug'
  id:
    | '__root__'
    | '/'
    | '/agbs'
    | '/bestellungen'
    | '/blog'
    | '/datenschutz'
    | '/impressum'
    | '/konto'
    | '/login'
    | '/marktplatz'
    | '/permdal'
    | '/produkte'
    | '/signup'
    | '/staffeln'
    | '/team'
    | '/verify-email'
    | '/zentrale'
    | '/angebote/$id'
    | '/zentrale/classic'
    | '/zentrale/compact'
    | '/zentrale/operations'
    | '/zentrale/'
    | '/users/$userId/$userSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbsRoute: typeof AgbsRoute
  BestellungenRoute: typeof BestellungenRoute
  BlogRoute: typeof BlogRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontoRoute: typeof KontoRoute
  LoginRoute: typeof LoginRoute
  MarktplatzRoute: typeof MarktplatzRoute
  PermdalRoute: typeof PermdalRoute
  ProdukteRoute: typeof ProdukteRoute
  SignupRoute: typeof SignupRoute
  StaffelnRoute: typeof StaffelnRoute
  TeamRoute: typeof TeamRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ZentraleRoute: typeof ZentraleRouteWithChildren
  AngeboteIdRoute: typeof AngeboteIdRoute
  UsersUserIdUserSlugRoute: typeof UsersUserIdUserSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zentrale': {
      id: '/zentrale'
      path: '/zentrale'
      fullPath: '/zentrale'
      preLoaderRoute: typeof ZentraleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffeln': {
      id: '/staffeln'
      path: '/staffeln'
      fullPath: '/staffeln'
      preLoaderRoute: typeof StaffelnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte': {
      id: '/produkte'
      path: '/produkte'
      fullPath: '/produkte'
      preLoaderRoute: typeof ProdukteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permdal': {
      id: '/permdal'
      path: '/permdal'
      fullPath: '/permdal'
      preLoaderRoute: typeof PermdalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marktplatz': {
      id: '/marktplatz'
      path: '/marktplatz'
      fullPath: '/marktplatz'
      preLoaderRoute: typeof MarktplatzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellungen': {
      id: '/bestellungen'
      path: '/bestellungen'
      fullPath: '/bestellungen'
      preLoaderRoute: typeof BestellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agbs': {
      id: '/agbs'
      path: '/agbs'
      fullPath: '/agbs'
      preLoaderRoute: typeof AgbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zentrale/': {
      id: '/zentrale/'
      path: '/'
      fullPath: '/zentrale/'
      preLoaderRoute: typeof ZentraleIndexRouteImport
      parentRoute: typeof ZentraleRoute
    }
    '/zentrale/operations': {
      id: '/zentrale/operations'
      path: '/operations'
      fullPath: '/zentrale/operations'
      preLoaderRoute: typeof ZentraleOperationsRouteImport
      parentRoute: typeof ZentraleRoute
    }
    '/zentrale/compact': {
      id: '/zentrale/compact'
      path: '/compact'
      fullPath: '/zentrale/compact'
      preLoaderRoute: typeof ZentraleCompactRouteImport
      parentRoute: typeof ZentraleRoute
    }
    '/zentrale/classic': {
      id: '/zentrale/classic'
      path: '/classic'
      fullPath: '/zentrale/classic'
      preLoaderRoute: typeof ZentraleClassicRouteImport
      parentRoute: typeof ZentraleRoute
    }
    '/angebote/$id': {
      id: '/angebote/$id'
      path: '/angebote/$id'
      fullPath: '/angebote/$id'
      preLoaderRoute: typeof AngeboteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/$userSlug': {
      id: '/users/$userId/$userSlug'
      path: '/users/$userId/$userSlug'
      fullPath: '/users/$userId/$userSlug'
      preLoaderRoute: typeof UsersUserIdUserSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ZentraleRouteChildren {
  ZentraleClassicRoute: typeof ZentraleClassicRoute
  ZentraleCompactRoute: typeof ZentraleCompactRoute
  ZentraleOperationsRoute: typeof ZentraleOperationsRoute
  ZentraleIndexRoute: typeof ZentraleIndexRoute
}

const ZentraleRouteChildren: ZentraleRouteChildren = {
  ZentraleClassicRoute: ZentraleClassicRoute,
  ZentraleCompactRoute: ZentraleCompactRoute,
  ZentraleOperationsRoute: ZentraleOperationsRoute,
  ZentraleIndexRoute: ZentraleIndexRoute,
}

const ZentraleRouteWithChildren = ZentraleRoute._addFileChildren(
  ZentraleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbsRoute: AgbsRoute,
  BestellungenRoute: BestellungenRoute,
  BlogRoute: BlogRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontoRoute: KontoRoute,
  LoginRoute: LoginRoute,
  MarktplatzRoute: MarktplatzRoute,
  PermdalRoute: PermdalRoute,
  ProdukteRoute: ProdukteRoute,
  SignupRoute: SignupRoute,
  StaffelnRoute: StaffelnRoute,
  TeamRoute: TeamRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ZentraleRoute: ZentraleRouteWithChildren,
  AngeboteIdRoute: AngeboteIdRoute,
  UsersUserIdUserSlugRoute: UsersUserIdUserSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
